base: 'https://team3.surfcamp.typo3.com/'
baseVariants:
  -
    condition: 'applicationContext == "Development/Devbox"'
    base: 'https://surfcamp-team3.ddev.site/'
dependencies:
  - surfcamp/restaurant
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
  -
    title: Deutsch
    enabled: true
    locale: de_DE
    hreflang: de-DE
    base: /de
    websiteTitle: Restaurant
    navigationTitle: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 1
websiteTitle: ''
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435