base: '%env(TYPO3_BASE_URL)%'
dependencies:
  - surfcamp/restaurant
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
  -
    title: Deutsch
    enabled: true
    locale: de_DE
    hreflang: de-DE
    base: /de/
    websiteTitle: Restaurant
    navigationTitle: ''
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 1
websiteTitle: ''
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435
