services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Surfcamp\Restaurant\:
    resource: '../Classes/*'

  Surfcamp\Restaurant\EventListener\ContentUsedOnPageListener:
    tags:
      - name: event.listener
        identifier: 'ContentUsedOnPageListener'